### ISSUE TITLE
It does not work correctly

### ISSUE THREAD

**Issue by ImNotKingFz** [respectdevelopment/rd_DiscordRPC#2]
Richpresence does not update the information, does not load.
![image](https://github.com/respectdevelopment/rd_DiscordRPC/assets/139582776/9eadfc17-36d3-468e-ad3d-4bf03a1417ae)

**Comment by respectdevelopment** [comment]
Any error in console? Do you have selected right framework in Config.lua?

**Comment by ImNotKingFz** [comment]
> Any error in console? Do you have selected right framework in Config.lua?

No, there is no error in the console, and I installed the correct framework

**Comment by respectdevelopment** [comment]
In that case, you must have made a mistake somewhere. The script is tested on QBCORE and ESX versions. (Everything is working on 100%)

**Comment by ImNotKingFz** [comment]
> In that case, you must have made a mistake somewhere. The script is tested on QBCORE and ESX versions. (Everything is working on 100%)

Do I have to disable qb-smallresources richpresence or not?

**Comment by ImNotKingFz** [comment]
because I activated it and now it works
